export interface DXCCInfo {
  prefix: string;
  name: string;
  flag: string;
  code: string;
}

// A robust but manageable map of prefixes to DXCC info
// Based on international callsign allocations
const DXCC_MAP: Record<string, { name: string; flag: string; code: string }> = {
  "DL": { name: "Germany", flag: "🇩🇪", code: "DE" },
  "DK": { name: "Germany", flag: "🇩🇪", code: "DE" },
  "DF": { name: "Germany", flag: "🇩🇪", code: "DE" },
  "DH": { name: "Germany", flag: "🇩🇪", code: "DE" },
  "DJ": { name: "Germany", flag: "🇩🇪", code: "DE" },
  "DA": { name: "Germany", flag: "🇩🇪", code: "DE" },
  "DB": { name: "Germany", flag: "🇩🇪", code: "DE" },
  "DC": { name: "Germany", flag: "🇩🇪", code: "DE" },
  "DD": { name: "Germany", flag: "🇩🇪", code: "DE" },
  "K": { name: "USA", flag: "🇺🇸", code: "US" },
  "W": { name: "USA", flag: "🇺🇸", code: "US" },
  "N": { name: "USA", flag: "🇺🇸", code: "US" },
  "AA": { name: "USA", flag: "🇺🇸", code: "US" },
  "G": { name: "United Kingdom", flag: "🇬🇧", code: "GB" },
  "M": { name: "United Kingdom", flag: "🇬🇧", code: "GB" },
  "2E": { name: "United Kingdom", flag: "🇬🇧", code: "GB" },
  "F": { name: "France", flag: "🇫🇷", code: "FR" },
  "TM": { name: "France", flag: "🇫🇷", code: "FR" },
  "I": { name: "Italy", flag: "🇮🇹", code: "IT" },
  "EA": { name: "Spain", flag: "🇪🇸", code: "ES" },
  "JA": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JR": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JE": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "PY": { name: "Brazil", flag: "🇧🇷", code: "BR" },
  "LU": { name: "Argentina", flag: "🇦🇷", code: "AR" },
  "VE": { name: "Canada", flag: "🇨🇦", code: "CA" },
  "VA": { name: "Canada", flag: "🇨🇦", code: "CA" },
  "VK": { name: "Australia", flag: "🇦🇺", code: "AU" },
  "ZL": { name: "New Zealand", flag: "🇳🇿", code: "NZ" },
  "RA": { name: "Russia", flag: "🇷🇺", code: "RU" },
  "UA": { name: "Russia", flag: "🇷🇺", code: "RU" },
  "UR": { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  "LY": { name: "Lithuania", flag: "🇱🇹", code: "LT" },
  "YL": { name: "Latvia", flag: "🇱🇻", code: "LV" },
  "ES": { name: "Estonia", flag: "🇪🇪", code: "EE" },
  "OH": { name: "Finland", flag: "🇫🇮", code: "FI" },
  "SM": { name: "Sweden", flag: "🇸🇪", code: "SE" },
  "LA": { name: "Norway", flag: "🇳🇴", code: "NO" },
  "OZ": { name: "Denmark", flag: "🇩🇰", code: "DK" },
  "HB": { name: "Switzerland", flag: "🇨🇭", code: "CH" },
  "OE": { name: "Austria", flag: "🇦🇹", code: "AT" },
  "PA": { name: "Netherlands", flag: "🇳🇱", code: "NL" },
  "ON": { name: "Belgium", flag: "🇧🇪", code: "BE" },
  "LX": { name: "Luxembourg", flag: "🇱🇺", code: "LU" },
  "SV": { name: "Greece", flag: "🇬🇷", code: "GR" },
  "SV5": { name: "Dodecanese", flag: "🇬🇷", code: "GR" },
  "SV9": { name: "Crete", flag: "🇬🇷", code: "GR" },
  "TA": { name: "Turkey", flag: "🇹🇷", code: "TR" },
  "LZ": { name: "Bulgaria", flag: "🇧🇬", code: "BG" },
  "YO": { name: "Romania", flag: "🇷🇴", code: "RO" },
  "HA": { name: "Hungary", flag: "🇭🇺", code: "HU" },
  "OK": { name: "Czech Republic", flag: "🇨🇿", code: "CZ" },
  "OM": { name: "Slovakia", flag: "🇸🇰", code: "SK" },
  "SP": { name: "Poland", flag: "🇵🇱", code: "PL" },
  "VU": { name: "India", flag: "🇮🇳", code: "IN" },
  "BY": { name: "China", flag: "🇨🇳", code: "CN" },
  "HL": { name: "South Korea", flag: "🇰🇷", code: "KR" },
  "XV": { name: "Vietnam", flag: "🇻🇳", code: "VN" },
  "HS": { name: "Thailand", flag: "🇹🇭", code: "TH" },
  "9M": { name: "Malaysia", flag: "🇲🇾", code: "MY" },
  "9V": { name: "Singapore", flag: "🇸🇬", code: "SG" },
  "YB": { name: "Indonesia", flag: "🇮🇩", code: "ID" },
  "DU": { name: "Philippines", flag: "🇵🇭", code: "PH" },
  "ZS": { name: "South Africa", flag: "🇿🇦", code: "ZA" },
  "5N": { name: "Nigeria", flag: "🇳🇬", code: "NG" },
  "ET": { name: "Ethiopia", flag: "🇪🇹", code: "ET" },
  "SU": { name: "Egypt", flag: "🇪🇬", code: "EG" },
  "CN": { name: "Morocco", flag: "🇲🇦", code: "MA" },
  "7X": { name: "Algeria", flag: "🇩🇿", code: "DZ" },
  "CX": { name: "Uruguay", flag: "🇺🇾", code: "UY" },
  "CE": { name: "Chile", flag: "🇨🇱", code: "CL" },
  "CP": { name: "Bolivia", flag: "🇧🇴", code: "BO" },
  "ZP": { name: "Paraguay", flag: "🇵🇾", code: "PY" },
  "OA": { name: "Peru", flag: "🇵🇪", code: "PE" },
  "HC": { name: "Ecuador", flag: "🇪🇨", code: "EC" },
  "HK": { name: "Colombia", flag: "🇨🇴", code: "CO" },
  "YV": { name: "Venezuela", flag: "🇻🇪", code: "VE" },
  "XE": { name: "Mexico", flag: "🇲🇽", code: "MX" },
  "TI": { name: "Costa Rica", flag: "🇨🇷", code: "CR" },
  "HP": { name: "Panama", flag: "🇵🇦", code: "PA" },
  "HI": { name: "Dominican Republic", flag: "🇩🇴", code: "DO" },
  "CO": { name: "Cuba", flag: "🇨🇺", code: "CU" },
  "TG": { name: "Guatemala", flag: "🇬🇹", code: "GT" },
  "YS": { name: "El Salvador", flag: "🇸🇻", code: "SV" },
  "HR": { name: "Honduras", flag: "🇭🇳", code: "HN" },
  "YN": { name: "Nicaragua", flag: "🇳🇮", code: "NI" },
  "V3": { name: "Belize", flag: "🇧🇿", code: "BZ" },
  "V4": { name: "St. Kitts & Nevis", flag: "🇰🇳", code: "KN" },
  "V5": { name: "Antigua & Barbuda", flag: "🇦🇬", code: "AG" },
  "V7": { name: "Marshall Islands", flag: "🇲🇭", code: "MH" },
  "V8": { name: "Brunei", flag: "🇧🇳", code: "BN" },
  "9H": { name: "Malta", flag: "🇲🇹", code: "MT" },
  "4X": { name: "Israel", flag: "🇮🇱", code: "IL" },
  "4Z": { name: "Israel", flag: "🇮🇱", code: "IL" },
  "OD": { name: "Lebanon", flag: "🇱🇧", code: "LB" },
  "JY": { name: "Jordan", flag: "🇯🇴", code: "JO" },
  "HZ": { name: "Saudi Arabia", flag: "🇸🇦", code: "SA" },
  "7Z": { name: "Saudi Arabia", flag: "🇸🇦", code: "SA" },
  "A6": { name: "UAE", flag: "🇦🇪", code: "AE" },
  "A7": { name: "Qatar", flag: "🇶🇦", code: "QA" },
  "A9": { name: "Bahrain", flag: "🇧🇭", code: "BH" },
  "9K": { name: "Kuwait", flag: "🇰🇼", code: "KW" },
  "S0": { name: "Western Sahara", flag: "🇪🇭", code: "EH" },
  "Z3": { name: "North Macedonia", flag: "🇲🇰", code: "MK" },
  "E7": { name: "Bosnia-Herzegovina", flag: "🇧🇦", code: "BA" },
  "9A": { name: "Croatia", flag: "🇭🇷", code: "HR" },
  "S5": { name: "Slovenia", flag: "🇸🇮", code: "SI" },
  "4O": { name: "Montenegro", flag: "🇲🇪", code: "ME" },
  "YU": { name: "Serbia", flag: "🇷🇸", code: "RS" },
  "Z6": { name: "Kosovo", flag: "🇽🇰", code: "XK" },
  "3A": { name: "Monaco", flag: "🇲🇨", code: "MC" },
  "C3": { name: "Andorra", flag: "🇦🇩", code: "AD" },
  "CU": { name: "Azores", flag: "🇵🇹", code: "PT" },
  "CT3": { name: "Madeira", flag: "🇵🇹", code: "PT" },
  "CT": { name: "Portugal", flag: "🇵🇹", code: "PT" },
  "ZA": { name: "Albania", flag: "🇦🇱", code: "AL" },
  "3V": { name: "Tunisia", flag: "🇹🇳", code: "TN" },
  "5T": { name: "Mauritania", flag: "🇲🇷", code: "MR" },
  "3X": { name: "Guinea", flag: "🇬🇳", code: "GN" },
  "J5": { name: "Guinea-Bissau", flag: "🇬🇼", code: "GW" },
  "TU": { name: "Ivory Coast", flag: "🇨🇮", code: "CI" },
  "EL": { name: "Liberia", flag: "🇱🇷", code: "LR" },
  "9L": { name: "Sierra Leone", flag: "🇸🇱", code: "SL" },
  "9G": { name: "Ghana", flag: "🇬🇭", code: "GH" },
  "5V": { name: "Togo", flag: "🇹🇬", code: "TG" },
  "TY": { name: "Benin", flag: "🇧🇯", code: "BJ" },
  "5U": { name: "Niger", flag: "🇳🇪", code: "NE" },
  "XT": { name: "Burkina Faso", flag: "🇧🇫", code: "BF" },
  "TT": { name: "Chad", flag: "🇹🇩", code: "TD" },
  "TL": { name: "Central Africa", flag: "🇨🇫", code: "CF" },
  "9Q": { name: "DR Congo", flag: "🇨🇩", code: "CD" },
  "TR": { name: "Gabon", flag: "🇬🇦", code: "GA" },
  "TJ": { name: "Cameroon", flag: "🇨🇲", code: "CM" },
  "TN": { name: "Congo", flag: "🇨🇬", code: "CG" },
  "3C": { name: "Equatorial Guinea", flag: "🇬🇶", code: "GQ" },
  "S9": { name: "Sao Tome & Principe", flag: "🇸🇹", code: "ST" },
  "D2": { name: "Angola", flag: "🇦🇴", code: "AO" },
  "V51": { name: "Namibia", flag: "🇳🇦", code: "NA" },
  "A2": { name: "Botswana", flag: "🇧🇼", code: "BW" },
  "7P": { name: "Lesotho", flag: "🇱🇸", code: "LS" },
  "3DA": { name: "Eswatini", flag: "🇸🇿", code: "SZ" },
  "ZE": { name: "Zimbabwe", flag: "🇿🇼", code: "ZW" },
  "9J": { name: "Zambia", flag: "🇿🇲", code: "ZM" },
  "9X": { name: "Rwanda", flag: "🇷🇼", code: "RW" },
  "9U": { name: "Burundi", flag: "🇧🇮", code: "BI" },
  "5X": { name: "Uganda", flag: "🇺🇬", code: "UG" },
  "5H": { name: "Tanzania", flag: "🇹🇿", code: "TZ" },
  "5Z": { name: "Kenya", flag: "🇰🇪", code: "KE" },
  "T5": { name: "Somalia", flag: "🇸🇴", code: "SO" },
  "ST": { name: "Sudan", flag: "🇸🇩", code: "SD" },
  "7Q": { name: "Malawi", flag: "🇲🇼", code: "MW" },
  "3B": { name: "Mauritius", flag: "🇲🇺", code: "MU" },
  "S7": { name: "Seychelles", flag: "🇸🇨", code: "SC" },
  "VQ9": { name: "Chagos", flag: "🇮🇴", code: "IO" },
  "FR": { name: "Reunion", flag: "🇷🇪", code: "RE" },
  "FT": { name: "TAAF", flag: "🇹🇫", code: "TF" },
  "6W": { name: "Senegal", flag: "🇸🇳", code: "SN" },
  "C5": { name: "Gambia", flag: "🇬🇲", code: "GM" },
  "D6": { name: "Comoros", flag: "🇰🇲", code: "KM" },
  "FH": { name: "Mayotte", flag: "🇾🇹", code: "YT" },
  "5R": { name: "Madagascar", flag: "🇲🇬", code: "MG" },
};

export const getCountryInfoByCallsign = (callsign: string): DXCCInfo => {
  if (!callsign) return { prefix: "", name: "Unknown", flag: "🏳️", code: "UN" };
  
  const upperCall = callsign.toUpperCase();
  
  // Try longest prefixes first (down to 1 char)
  for (let len = 4; len >= 1; len--) {
    const prefix = upperCall.substring(0, len);
    if (DXCC_MAP[prefix]) {
      return {
        prefix,
        ...DXCC_MAP[prefix]
      };
    }
  }
  
  return { prefix: "", name: "Unknown", flag: "🏳️", code: "UN" };
};
