export interface DXCCInfo {
  prefix: string;
  name: string;
  flag: string;
  code: string;
}

// Comprehensive map of international DXCC entities and ITU prefix allocations
export const DXCC_MAP: Record<string, { name: string; flag: string; code: string }> = {
  // --- Germany ---
  "DA": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DB": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DC": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DD": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DF": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DG": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DH": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DJ": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DK": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DL": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DM": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DN": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DO": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DP": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DQ": { name: "Deutschland", flag: "🇩🇪", code: "DE" },
  "DR": { name: "Deutschland", flag: "🇩🇪", code: "DE" },

  // --- United Kingdom & Crown Dependencies / Overseas ---
  "2D": { name: "Isle of Man", flag: "🇮🇲", code: "IM" },
  "GD": { name: "Isle of Man", flag: "🇮🇲", code: "IM" },
  "GT": { name: "Isle of Man", flag: "🇮🇲", code: "IM" },
  "MD": { name: "Isle of Man", flag: "🇮🇲", code: "IM" },
  "2J": { name: "Jersey", flag: "🇯🇪", code: "JE" },
  "GJ": { name: "Jersey", flag: "🇯🇪", code: "JE" },
  "GH": { name: "Jersey", flag: "🇯🇪", code: "JE" },
  "MJ": { name: "Jersey", flag: "🇯🇪", code: "JE" },
  "2U": { name: "Guernsey", flag: "🇬🇬", code: "GG" },
  "GU": { name: "Guernsey", flag: "🇬🇬", code: "GG" },
  "GP": { name: "Guernsey", flag: "🇬🇬", code: "GG" },
  "MU": { name: "Guernsey", flag: "🇬🇬", code: "GG" },
  "2I": { name: "Nordirland", flag: "🇬🇧", code: "GB-NIR" },
  "GI": { name: "Nordirland", flag: "🇬🇧", code: "GB-NIR" },
  "GN": { name: "Nordirland", flag: "🇬🇧", code: "GB-NIR" },
  "MI": { name: "Nordirland", flag: "🇬🇧", code: "GB-NIR" },
  "2M": { name: "Schottland", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", code: "GB-SCT" },
  "GM": { name: "Schottland", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", code: "GB-SCT" },
  "GS": { name: "Schottland", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", code: "GB-SCT" },
  "MM": { name: "Schottland", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", code: "GB-SCT" },
  "2W": { name: "Wales", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", code: "GB-WLS" },
  "GW": { name: "Wales", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", code: "GB-WLS" },
  "GC": { name: "Wales", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", code: "GB-WLS" },
  "MW": { name: "Wales", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", code: "GB-WLS" },
  "2E": { name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", code: "GB-ENG" },
  "G": { name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", code: "GB-ENG" },
  "GX": { name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", code: "GB-ENG" },
  "M": { name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", code: "GB-ENG" },
  "MX": { name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", code: "GB-ENG" },
  "ZB2": { name: "Gibraltar", flag: "🇬🇮", code: "GI" },
  "ZB": { name: "Gibraltar", flag: "🇬🇮", code: "GI" },
  "VP8": { name: "Falklandinseln", flag: "🇫🇰", code: "FK" },
  "VP9": { name: "Bermuda", flag: "🇧🇲", code: "BM" },
  "ZF": { name: "Kaimaninseln", flag: "🇰🇾", code: "KY" },
  "VP2M": { name: "Montserrat", flag: "🇲🇸", code: "MS" },
  "VP2E": { name: "Anguilla", flag: "🇦🇮", code: "AI" },
  "VP2V": { name: "Britische Jungferninseln", flag: "🇻🇬", code: "VG" },
  "VP5": { name: "Turks- & Caicosinseln", flag: "🇹🇨", code: "TC" },
  "ZD7": { name: "St. Helena", flag: "🇸🇭", code: "SH" },
  "ZD8": { name: "Ascension Island", flag: "🇦🇨", code: "AC" },
  "ZD9": { name: "Tristan da Cunha", flag: "🇹🇦", code: "TA" },
  "VP6": { name: "Pitcairn", flag: "🇵🇳", code: "PN" },
  "ZC4": { name: "UK Bases Zypern", flag: "🇨🇾", code: "CY" },

  // --- Spain & Islands ---
  "EA6": { name: "Balearen", flag: "🇪🇸", code: "ES" },
  "EB6": { name: "Balearen", flag: "🇪🇸", code: "ES" },
  "EC6": { name: "Balearen", flag: "🇪🇸", code: "ES" },
  "ED6": { name: "Balearen", flag: "🇪🇸", code: "ES" },
  "EE6": { name: "Balearen", flag: "🇪🇸", code: "ES" },
  "EF6": { name: "Balearen", flag: "🇪🇸", code: "ES" },
  "EA8": { name: "Kanarische Inseln", flag: "🇮🇨", code: "IC" },
  "EB8": { name: "Kanarische Inseln", flag: "🇮🇨", code: "IC" },
  "EC8": { name: "Kanarische Inseln", flag: "🇮🇨", code: "IC" },
  "ED8": { name: "Kanarische Inseln", flag: "🇮🇨", code: "IC" },
  "EE8": { name: "Kanarische Inseln", flag: "🇮🇨", code: "IC" },
  "EF8": { name: "Kanarische Inseln", flag: "🇮🇨", code: "IC" },
  "EA9": { name: "Ceuta & Melilla", flag: "🇪🇸", code: "ES" },
  "EB9": { name: "Ceuta & Melilla", flag: "🇪🇸", code: "ES" },
  "EC9": { name: "Ceuta & Melilla", flag: "🇪🇸", code: "ES" },
  "ED9": { name: "Ceuta & Melilla", flag: "🇪🇸", code: "ES" },
  "EA": { name: "Spanien", flag: "🇪🇸", code: "ES" },
  "EB": { name: "Spanien", flag: "🇪🇸", code: "ES" },
  "EC": { name: "Spanien", flag: "🇪🇸", code: "ES" },
  "ED": { name: "Spanien", flag: "🇪🇸", code: "ES" },
  "EE": { name: "Spanien", flag: "🇪🇸", code: "ES" },
  "EF": { name: "Spanien", flag: "🇪🇸", code: "ES" },
  "EG": { name: "Spanien", flag: "🇪🇸", code: "ES" },
  "EH": { name: "Spanien", flag: "🇪🇸", code: "ES" },
  "AM": { name: "Spanien", flag: "🇪🇸", code: "ES" },
  "AN": { name: "Spanien", flag: "🇪🇸", code: "ES" },
  "AO": { name: "Spanien", flag: "🇪🇸", code: "ES" },

  // --- Portugal & Islands ---
  "CT3": { name: "Madeira", flag: "🇵🇹", code: "PT" },
  "CS3": { name: "Madeira", flag: "🇵🇹", code: "PT" },
  "CR3": { name: "Madeira", flag: "🇵🇹", code: "PT" },
  "CQ3": { name: "Madeira", flag: "🇵🇹", code: "PT" },
  "CU": { name: "Azoren", flag: "🇵🇹", code: "PT" },
  "CT": { name: "Portugal", flag: "🇵🇹", code: "PT" },
  "CS": { name: "Portugal", flag: "🇵🇹", code: "PT" },
  "CR": { name: "Portugal", flag: "🇵🇹", code: "PT" },
  "CQ": { name: "Portugal", flag: "🇵🇹", code: "PT" },

  // --- France & Overseas ---
  "TK": { name: "Korsika", flag: "🇫🇷", code: "FR" },
  "FG": { name: "Guadeloupe", flag: "🇬🇵", code: "GP" },
  "FM": { name: "Martinique", flag: "🇲🇶", code: "MQ" },
  "FS": { name: "Saint-Martin", flag: "🇲🇫", code: "MF" },
  "FY": { name: "Französisch-Guayana", flag: "🇬🇫", code: "GF" },
  "FP": { name: "St. Pierre & Miquelon", flag: "🇵🇲", code: "PM" },
  "FK": { name: "Neukaledonien", flag: "🇳🇨", code: "NC" },
  "FO": { name: "Französisch-Polynesien", flag: "🇵🇫", code: "PF" },
  "FW": { name: "Wallis & Futuna", flag: "🇼🇫", code: "WF" },
  "FH": { name: "Mayotte", flag: "🇾🇹", code: "YT" },
  "FR": { name: "Réunion", flag: "🇷🇪", code: "RE" },
  "FT": { name: "TAAF (Südgebiete)", flag: "🇹🇫", code: "TF" },
  "F": { name: "Frankreich", flag: "🇫🇷", code: "FR" },
  "TM": { name: "Frankreich", flag: "🇫🇷", code: "FR" },
  "TO": { name: "Frankreich", flag: "🇫🇷", code: "FR" },
  "TP": { name: "Frankreich", flag: "🇫🇷", code: "FR" },
  "TQ": { name: "Frankreich", flag: "🇫🇷", code: "FR" },
  "TV": { name: "Frankreich", flag: "🇫🇷", code: "FR" },
  "HW": { name: "Frankreich", flag: "🇫🇷", code: "FR" },
  "HY": { name: "Frankreich", flag: "🇫🇷", code: "FR" },

  // --- Italy & Micro-States ---
  "IS0": { name: "Sardinien", flag: "🇮🇹", code: "IT" },
  "IB0": { name: "Sardinien", flag: "🇮🇹", code: "IT" },
  "IM0": { name: "Sardinien", flag: "🇮🇹", code: "IT" },
  "IT9": { name: "Sizilien", flag: "🇮🇹", code: "IT" },
  "IF9": { name: "Sizilien", flag: "🇮🇹", code: "IT" },
  "HV": { name: "Vatikanstadt", flag: "🇻🇦", code: "VA" },
  "T7": { name: "San Marino", flag: "🇸🇲", code: "SM" },
  "1A0": { name: "Malteserorden", flag: "🇲🇹", code: "MT" },
  "1A": { name: "Malteserorden", flag: "🇲🇹", code: "MT" },
  "I": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IK": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IZ": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IU": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IW": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IT": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IN": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IQ": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IA": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IB": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "ID": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IE": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IF": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IG": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IH": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IL": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IM": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IP": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IR": { name: "Italien", flag: "🇮🇹", code: "IT" },
  "IS": { name: "Italien", flag: "🇮🇹", code: "IT" },

  // --- Switzerland & Austria ---
  "HB0": { name: "Liechtenstein", flag: "🇱🇮", code: "LI" },
  "HB9": { name: "Schweiz", flag: "🇨🇭", code: "CH" },
  "HB3": { name: "Schweiz", flag: "🇨🇭", code: "CH" },
  "HB": { name: "Schweiz", flag: "🇨🇭", code: "CH" },
  "OE": { name: "Österreich", flag: "🇦🇹", code: "AT" },

  // --- Benelux ---
  "PA": { name: "Niederlande", flag: "🇳🇱", code: "NL" },
  "PB": { name: "Niederlande", flag: "🇳🇱", code: "NL" },
  "PC": { name: "Niederlande", flag: "🇳🇱", code: "NL" },
  "PD": { name: "Niederlande", flag: "🇳🇱", code: "NL" },
  "PE": { name: "Niederlande", flag: "🇳🇱", code: "NL" },
  "PF": { name: "Niederlande", flag: "🇳🇱", code: "NL" },
  "PG": { name: "Niederlande", flag: "🇳🇱", code: "NL" },
  "PH": { name: "Niederlande", flag: "🇳🇱", code: "NL" },
  "PI": { name: "Niederlande", flag: "🇳🇱", code: "NL" },
  "PJ2": { name: "Curaçao", flag: "🇨🇼", code: "CW" },
  "PJ4": { name: "Bonaire", flag: "🇧🇶", code: "BQ" },
  "PJ7": { name: "Sint Maarten", flag: "🇸🇽", code: "SX" },
  "PJ5": { name: "Saba & St. Eustatius", flag: "🇧🇶", code: "BQ" },
  "PJ6": { name: "Saba & St. Eustatius", flag: "🇧🇶", code: "BQ" },
  "ON": { name: "Belgien", flag: "🇧🇪", code: "BE" },
  "OO": { name: "Belgien", flag: "🇧🇪", code: "BE" },
  "OP": { name: "Belgien", flag: "🇧🇪", code: "BE" },
  "OQ": { name: "Belgien", flag: "🇧🇪", code: "BE" },
  "OR": { name: "Belgien", flag: "🇧🇪", code: "BE" },
  "OS": { name: "Belgien", flag: "🇧🇪", code: "BE" },
  "OT": { name: "Belgien", flag: "🇧🇪", code: "BE" },
  "LX": { name: "Luxemburg", flag: "🇱🇺", code: "LU" },
  "EI": { name: "Irland", flag: "🇮🇪", code: "IE" },
  "EJ": { name: "Irland", flag: "🇮🇪", code: "IE" },

  // --- Scandinavia & Nordics ---
  "OH0": { name: "Åland-Inseln", flag: "🇦🇽", code: "AX" },
  "OJ0": { name: "Market Reef", flag: "🇦🇽", code: "AX" },
  "OH": { name: "Finnland", flag: "🇫🇮", code: "FI" },
  "OF": { name: "Finnland", flag: "🇫🇮", code: "FI" },
  "OG": { name: "Finnland", flag: "🇫🇮", code: "FI" },
  "OI": { name: "Finnland", flag: "🇫🇮", code: "FI" },
  "JW": { name: "Spitzbergen", flag: "🇸🇯", code: "SJ" },
  "JX": { name: "Jan Mayen", flag: "🇸🇯", code: "SJ" },
  "LA": { name: "Norwegen", flag: "🇳🇴", code: "NO" },
  "LB": { name: "Norwegen", flag: "🇳🇴", code: "NO" },
  "LC": { name: "Norwegen", flag: "🇳🇴", code: "NO" },
  "LD": { name: "Norwegen", flag: "🇳🇴", code: "NO" },
  "LE": { name: "Norwegen", flag: "🇳🇴", code: "NO" },
  "LF": { name: "Norwegen", flag: "🇳🇴", code: "NO" },
  "LG": { name: "Norwegen", flag: "🇳🇴", code: "NO" },
  "LH": { name: "Norwegen", flag: "🇳🇴", code: "NO" },
  "LI": { name: "Norwegen", flag: "🇳🇴", code: "NO" },
  "LJ": { name: "Norwegen", flag: "🇳🇴", code: "NO" },
  "LN": { name: "Norwegen", flag: "🇳🇴", code: "NO" },
  "SM": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "SA": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "SB": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "SC": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "SD": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "SE": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "SF": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "SG": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "SH": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "SI": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "SJ": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "SK": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "SL": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "7S": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "8S": { name: "Schweden", flag: "🇸🇪", code: "SE" },
  "OX": { name: "Grönland", flag: "🇬🇱", code: "GL" },
  "XP": { name: "Grönland", flag: "🇬🇱", code: "GL" },
  "OY": { name: "Färöer-Inseln", flag: "🇫🇴", code: "FO" },
  "OZ": { name: "Dänemark", flag: "🇩🇰", code: "DK" },
  "OU": { name: "Dänemark", flag: "🇩🇰", code: "DK" },
  "OV": { name: "Dänemark", flag: "🇩🇰", code: "DK" },
  "5P": { name: "Dänemark", flag: "🇩🇰", code: "DK" },
  "5Q": { name: "Dänemark", flag: "🇩🇰", code: "DK" },
  "TF": { name: "Island", flag: "🇮🇸", code: "IS" },

  // --- Central & Eastern Europe, Balkans ---
  "SP": { name: "Polen", flag: "🇵🇱", code: "PL" },
  "SQ": { name: "Polen", flag: "🇵🇱", code: "PL" },
  "SO": { name: "Polen", flag: "🇵🇱", code: "PL" },
  "SN": { name: "Polen", flag: "🇵🇱", code: "PL" },
  "SR": { name: "Polen", flag: "🇵🇱", code: "PL" },
  "HF": { name: "Polen", flag: "🇵🇱", code: "PL" },
  "3Z": { name: "Polen", flag: "🇵🇱", code: "PL" },
  "OK": { name: "Tschechien", flag: "🇨🇿", code: "CZ" },
  "OL": { name: "Tschechien", flag: "🇨🇿", code: "CZ" },
  "OM": { name: "Slowakei", flag: "🇸🇰", code: "SK" },
  "HA": { name: "Ungarn", flag: "🇭🇺", code: "HU" },
  "HG": { name: "Ungarn", flag: "🇭🇺", code: "HU" },
  "YO": { name: "Rumänien", flag: "🇷🇴", code: "RO" },
  "YP": { name: "Rumänien", flag: "🇷🇴", code: "RO" },
  "YQ": { name: "Rumänien", flag: "🇷🇴", code: "RO" },
  "YR": { name: "Rumänien", flag: "🇷🇴", code: "RO" },
  "LZ": { name: "Bulgarien", flag: "🇧🇬", code: "BG" },
  "SV5": { name: "Dodekanes", flag: "🇬🇷", code: "GR" },
  "SV9": { name: "Kreta", flag: "🇬🇷", code: "GR" },
  "SV": { name: "Griechenland", flag: "🇬🇷", code: "GR" },
  "SX": { name: "Griechenland", flag: "🇬🇷", code: "GR" },
  "SY": { name: "Griechenland", flag: "🇬🇷", code: "GR" },
  "SZ": { name: "Griechenland", flag: "🇬🇷", code: "GR" },
  "J4": { name: "Griechenland", flag: "🇬🇷", code: "GR" },
  "9A": { name: "Kroatien", flag: "🇭🇷", code: "HR" },
  "S5": { name: "Slowenien", flag: "🇸🇮", code: "SI" },
  "E7": { name: "Bosnien-Herzegowina", flag: "🇧🇦", code: "BA" },
  "YU": { name: "Serbien", flag: "🇷🇸", code: "RS" },
  "YT": { name: "Serbien", flag: "🇷🇸", code: "RS" },
  "4O": { name: "Montenegro", flag: "🇲🇪", code: "ME" },
  "Z3": { name: "Nordmazedonien", flag: "🇲🇰", code: "MK" },
  "Z6": { name: "Kosovo", flag: "🇽🇰", code: "XK" },
  "ZA": { name: "Albanien", flag: "🇦🇱", code: "AL" },
  "3A": { name: "Monaco", flag: "🇲🇨", code: "MC" },
  "C3": { name: "Andorra", flag: "🇦🇩", code: "AD" },
  "ER": { name: "Moldau", flag: "🇲🇩", code: "MD" },
  "UR": { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  "US": { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  "UT": { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  "UU": { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  "UV": { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  "UW": { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  "UX": { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  "UY": { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  "UZ": { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  "EM": { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  "EN": { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  "EO": { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  "EU": { name: "Belarus", flag: "🇧🇾", code: "BY" },
  "EV": { name: "Belarus", flag: "🇧🇾", code: "BY" },
  "EW": { name: "Belarus", flag: "🇧🇾", code: "BY" },
  "ES": { name: "Estland", flag: "🇪🇪", code: "EE" },
  "YL": { name: "Lettland", flag: "🇱🇻", code: "LV" },
  "LY": { name: "Litauen", flag: "🇱🇹", code: "LT" },

  // --- Russia & Kaliningrad ---
  "UA2": { name: "Kaliningrad", flag: "🇷🇺", code: "RU" },
  "RA2": { name: "Kaliningrad", flag: "🇷🇺", code: "RU" },
  "RN2": { name: "Kaliningrad", flag: "🇷🇺", code: "RU" },
  "UA": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RA": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RB": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RC": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RD": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RE": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RF": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RG": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RH": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RI": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RJ": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RK": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RL": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RM": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RN": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RO": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RP": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RQ": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RR": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RS": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RT": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RU": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RV": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RW": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RX": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RY": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "RZ": { name: "Russland", flag: "🇷🇺", code: "RU" },
  "R": { name: "Russland", flag: "🇷🇺", code: "RU" },

  // --- USA & Possessions ---
  "KL7": { name: "Alaska", flag: "🇺🇸", code: "US" },
  "AL7": { name: "Alaska", flag: "🇺🇸", code: "US" },
  "NL7": { name: "Alaska", flag: "🇺🇸", code: "US" },
  "WL7": { name: "Alaska", flag: "🇺🇸", code: "US" },
  "KL": { name: "Alaska", flag: "🇺🇸", code: "US" },
  "AL": { name: "Alaska", flag: "🇺🇸", code: "US" },
  "NL": { name: "Alaska", flag: "🇺🇸", code: "US" },
  "WL": { name: "Alaska", flag: "🇺🇸", code: "US" },
  "KH6": { name: "Hawaii", flag: "🇺🇸", code: "US" },
  "AH6": { name: "Hawaii", flag: "🇺🇸", code: "US" },
  "NH6": { name: "Hawaii", flag: "🇺🇸", code: "US" },
  "WH6": { name: "Hawaii", flag: "🇺🇸", code: "US" },
  "KH": { name: "Hawaii", flag: "🇺🇸", code: "US" },
  "AH": { name: "Hawaii", flag: "🇺🇸", code: "US" },
  "NH": { name: "Hawaii", flag: "🇺🇸", code: "US" },
  "WH": { name: "Hawaii", flag: "🇺🇸", code: "US" },
  "KP4": { name: "Puerto Rico", flag: "🇵🇷", code: "PR" },
  "WP4": { name: "Puerto Rico", flag: "🇵🇷", code: "PR" },
  "NP4": { name: "Puerto Rico", flag: "🇵🇷", code: "PR" },
  "KP2": { name: "Amerik. Jungferninseln", flag: "🇻🇮", code: "VI" },
  "WP2": { name: "Amerik. Jungferninseln", flag: "🇻🇮", code: "VI" },
  "NP2": { name: "Amerik. Jungferninseln", flag: "🇻🇮", code: "VI" },
  "KH2": { name: "Guam", flag: "🇬🇺", code: "GU" },
  "AH2": { name: "Guam", flag: "🇬🇺", code: "GU" },
  "NH2": { name: "Guam", flag: "🇬🇺", code: "GU" },
  "WH2": { name: "Guam", flag: "🇬🇺", code: "GU" },
  "KH0": { name: "Marianen", flag: "🇲🇵", code: "MP" },
  "AH0": { name: "Marianen", flag: "🇲🇵", code: "MP" },
  "NH0": { name: "Marianen", flag: "🇲🇵", code: "MP" },
  "WH0": { name: "Marianen", flag: "🇲🇵", code: "MP" },
  "KH8": { name: "Amerik.-Samoa", flag: "🇦🇸", code: "AS" },
  "K": { name: "USA", flag: "🇺🇸", code: "US" },
  "W": { name: "USA", flag: "🇺🇸", code: "US" },
  "N": { name: "USA", flag: "🇺🇸", code: "US" },
  "AA": { name: "USA", flag: "🇺🇸", code: "US" },
  "AB": { name: "USA", flag: "🇺🇸", code: "US" },
  "AC": { name: "USA", flag: "🇺🇸", code: "US" },
  "AD": { name: "USA", flag: "🇺🇸", code: "US" },
  "AE": { name: "USA", flag: "🇺🇸", code: "US" },
  "AF": { name: "USA", flag: "🇺🇸", code: "US" },
  "AG": { name: "USA", flag: "🇺🇸", code: "US" },
  "AI": { name: "USA", flag: "🇺🇸", code: "US" },
  "AJ": { name: "USA", flag: "🇺🇸", code: "US" },
  "AK": { name: "USA", flag: "🇺🇸", code: "US" },
  "NA": { name: "USA", flag: "🇺🇸", code: "US" },
  "NB": { name: "USA", flag: "🇺🇸", code: "US" },
  "NC": { name: "USA", flag: "🇺🇸", code: "US" },
  "ND": { name: "USA", flag: "🇺🇸", code: "US" },
  "NE": { name: "USA", flag: "🇺🇸", code: "US" },
  "NF": { name: "USA", flag: "🇺🇸", code: "US" },
  "NG": { name: "USA", flag: "🇺🇸", code: "US" },
  "NI": { name: "USA", flag: "🇺🇸", code: "US" },
  "NJ": { name: "USA", flag: "🇺🇸", code: "US" },
  "NK": { name: "USA", flag: "🇺🇸", code: "US" },
  "WA": { name: "USA", flag: "🇺🇸", code: "US" },
  "WB": { name: "USA", flag: "🇺🇸", code: "US" },
  "WC": { name: "USA", flag: "🇺🇸", code: "US" },
  "WD": { name: "USA", flag: "🇺🇸", code: "US" },
  "WE": { name: "USA", flag: "🇺🇸", code: "US" },
  "WF": { name: "USA", flag: "🇺🇸", code: "US" },
  "WG": { name: "USA", flag: "🇺🇸", code: "US" },
  "WI": { name: "USA", flag: "🇺🇸", code: "US" },
  "WJ": { name: "USA", flag: "🇺🇸", code: "US" },
  "WK": { name: "USA", flag: "🇺🇸", code: "US" },
  "KA": { name: "USA", flag: "🇺🇸", code: "US" },
  "KB": { name: "USA", flag: "🇺🇸", code: "US" },
  "KC": { name: "USA", flag: "🇺🇸", code: "US" },
  "KD": { name: "USA", flag: "🇺🇸", code: "US" },
  "KE": { name: "USA", flag: "🇺🇸", code: "US" },
  "KF": { name: "USA", flag: "🇺🇸", code: "US" },
  "KG": { name: "USA", flag: "🇺🇸", code: "US" },
  "KI": { name: "USA", flag: "🇺🇸", code: "US" },
  "KJ": { name: "USA", flag: "🇺🇸", code: "US" },
  "KK": { name: "USA", flag: "🇺🇸", code: "US" },

  // --- Canada ---
  "CY0": { name: "Sable Island", flag: "🇨🇦", code: "CA" },
  "CY9": { name: "St. Paul Island", flag: "🇨🇦", code: "CA" },
  "VE": { name: "Kanada", flag: "🇨🇦", code: "CA" },
  "VA": { name: "Kanada", flag: "🇨🇦", code: "CA" },
  "VO": { name: "Kanada", flag: "🇨🇦", code: "CA" },
  "VY": { name: "Kanada", flag: "🇨🇦", code: "CA" },
  "CY": { name: "Kanada", flag: "🇨🇦", code: "CA" },
  "CZ": { name: "Kanada", flag: "🇨🇦", code: "CA" },

  // --- Japan & East Asia ---
  "JA": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JR": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JE": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JF": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JG": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JH": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JI": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JJ": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JK": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JL": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JM": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JN": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JO": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JP": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JQ": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "JS": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "7J": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "7K": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "7L": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "7M": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "7N": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "8J": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "8K": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "8N": { name: "Japan", flag: "🇯🇵", code: "JP" },
  "HL": { name: "Südkorea", flag: "🇰🇷", code: "KR" },
  "DS": { name: "Südkorea", flag: "🇰🇷", code: "KR" },
  "DT": { name: "Südkorea", flag: "🇰🇷", code: "KR" },
  "D7": { name: "Südkorea", flag: "🇰🇷", code: "KR" },
  "6K": { name: "Südkorea", flag: "🇰🇷", code: "KR" },
  "P5": { name: "Nordkorea", flag: "🇰🇵", code: "KP" },
  "BY": { name: "China", flag: "🇨🇳", code: "CN" },
  "BA": { name: "China", flag: "🇨🇳", code: "CN" },
  "BD": { name: "China", flag: "🇨🇳", code: "CN" },
  "BG": { name: "China", flag: "🇨🇳", code: "CN" },
  "BH": { name: "China", flag: "🇨🇳", code: "CN" },
  "BI": { name: "China", flag: "🇨🇳", code: "CN" },
  "BJ": { name: "China", flag: "🇨🇳", code: "CN" },
  "BL": { name: "China", flag: "🇨🇳", code: "CN" },
  "BT": { name: "China", flag: "🇨🇳", code: "CN" },
  "BV": { name: "Taiwan", flag: "🇹🇼", code: "TW" },
  "BX": { name: "Taiwan", flag: "🇹🇼", code: "TW" },
  "VR2": { name: "Hongkong", flag: "🇭🇰", code: "HK" },
  "XX9": { name: "Macau", flag: "🇲🇴", code: "MO" },
  "JT": { name: "Mongolei", flag: "🇲🇳", code: "MN" },
  "JV": { name: "Mongolei", flag: "🇲🇳", code: "MN" },
  "JU": { name: "Mongolei", flag: "🇲🇳", code: "MN" },

  // --- Australia, New Zealand & Pacific ---
  "VK9N": { name: "Norfolkinsel", flag: "🇳🇫", code: "NF" },
  "VK9C": { name: "Kokosinseln", flag: "🇨🇨", code: "CC" },
  "VK9X": { name: "Weihnachtsinsel", flag: "🇨🇽", code: "CX" },
  "VK9L": { name: "Lord-Howe-Insel", flag: "🇦🇺", code: "AU" },
  "VK0": { name: "Heard / Macquarie", flag: "🇦🇶", code: "AQ" },
  "VK": { name: "Australien", flag: "🇦🇺", code: "AU" },
  "AX": { name: "Australien", flag: "🇦🇺", code: "AU" },
  "VI": { name: "Australien", flag: "🇦🇺", code: "AU" },
  "ZL7": { name: "Chatham-Inseln", flag: "🇳🇿", code: "NZ" },
  "ZL8": { name: "Kermadecinseln", flag: "🇳🇿", code: "NZ" },
  "ZL9": { name: "Auckland- & Campbell-Inseln", flag: "🇳🇿", code: "NZ" },
  "ZL": { name: "Neuseeland", flag: "🇳🇿", code: "NZ" },
  "ZM": { name: "Neuseeland", flag: "🇳🇿", code: "NZ" },
  "P2": { name: "Papua-Neuguinea", flag: "🇵🇬", code: "PG" },
  "YJ": { name: "Vanuatu", flag: "🇻🇺", code: "VU" },
  "3D2": { name: "Fidschi", flag: "🇫🇯", code: "FJ" },
  "5W": { name: "Samoa", flag: "🇼🇸", code: "WS" },
  "A3": { name: "Tonga", flag: "🇹🇴", code: "TO" },
  "T2": { name: "Tuvalu", flag: "🇹🇻", code: "TV" },
  "T30": { name: "West-Kiribati", flag: "🇰🇮", code: "KI" },
  "T31": { name: "Zentral-Kiribati", flag: "🇰🇮", code: "KI" },
  "T32": { name: "Ost-Kiribati", flag: "🇰🇮", code: "KI" },
  "C2": { name: "Nauru", flag: "🇳🇷", code: "NR" },
  "V7": { name: "Marshallinseln", flag: "🇲🇭", code: "MH" },
  "V6": { name: "Mikronesien", flag: "🇫🇲", code: "FM" },
  "E5": { name: "Cookinseln", flag: "🇨🇰", code: "CK" },
  "E6": { name: "Niue", flag: "🇳🇺", code: "NU" },
  "H4": { name: "Salomonen", flag: "🇸🇧", code: "SB" },

  // --- South America ---
  "PY0F": { name: "Fernando de Noronha", flag: "🇧🇷", code: "BR" },
  "PY0T": { name: "Trindade & Martim Vaz", flag: "🇧🇷", code: "BR" },
  "PY0S": { name: "St. Peter & Paul", flag: "🇧🇷", code: "BR" },
  "PY": { name: "Brasilien", flag: "🇧🇷", code: "BR" },
  "PP": { name: "Brasilien", flag: "🇧🇷", code: "BR" },
  "PR": { name: "Brasilien", flag: "🇧🇷", code: "BR" },
  "PS": { name: "Brasilien", flag: "🇧🇷", code: "BR" },
  "PT": { name: "Brasilien", flag: "🇧🇷", code: "BR" },
  "PU": { name: "Brasilien", flag: "🇧🇷", code: "BR" },
  "PV": { name: "Brasilien", flag: "🇧🇷", code: "BR" },
  "PW": { name: "Brasilien", flag: "🇧🇷", code: "BR" },
  "PX": { name: "Brasilien", flag: "🇧🇷", code: "BR" },
  "ZY": { name: "Brasilien", flag: "🇧🇷", code: "BR" },
  "ZZ": { name: "Brasilien", flag: "🇧🇷", code: "BR" },
  "LU": { name: "Argentinien", flag: "🇦🇷", code: "AR" },
  "LW": { name: "Argentinien", flag: "🇦🇷", code: "AR" },
  "AY": { name: "Argentinien", flag: "🇦🇷", code: "AR" },
  "AZ": { name: "Argentinien", flag: "🇦🇷", code: "AR" },
  "CE0Y": { name: "Osterinsel", flag: "🇨🇱", code: "CL" },
  "CE0Z": { name: "Juan Fernandez", flag: "🇨🇱", code: "CL" },
  "CE": { name: "Chile", flag: "🇨🇱", code: "CL" },
  "CA": { name: "Chile", flag: "🇨🇱", code: "CL" },
  "CB": { name: "Chile", flag: "🇨🇱", code: "CL" },
  "CD": { name: "Chile", flag: "🇨🇱", code: "CL" },
  "XQ": { name: "Chile", flag: "🇨🇱", code: "CL" },
  "3G": { name: "Chile", flag: "🇨🇱", code: "CL" },
  "CP": { name: "Bolivien", flag: "🇧🇴", code: "BO" },
  "ZP": { name: "Paraguay", flag: "🇵🇾", code: "PY" },
  "OA": { name: "Peru", flag: "🇵🇪", code: "PE" },
  "OB": { name: "Peru", flag: "🇵🇪", code: "PE" },
  "OC": { name: "Peru", flag: "🇵🇪", code: "PE" },
  "4T": { name: "Peru", flag: "🇵🇪", code: "PE" },
  "HC8": { name: "Galapagos", flag: "🇪🇨", code: "EC" },
  "HC": { name: "Ecuador", flag: "🇪🇨", code: "EC" },
  "HD": { name: "Ecuador", flag: "🇪🇨", code: "EC" },
  "HK0": { name: "San Andres / Malpelo", flag: "🇨🇴", code: "CO" },
  "HK": { name: "Kolumbien", flag: "🇨🇴", code: "CO" },
  "HJ": { name: "Kolumbien", flag: "🇨🇴", code: "CO" },
  "5J": { name: "Kolumbien", flag: "🇨🇴", code: "CO" },
  "5K": { name: "Kolumbien", flag: "🇨🇴", code: "CO" },
  "YV0": { name: "Aves Island", flag: "🇻🇪", code: "VE" },
  "YV": { name: "Venezuela", flag: "🇻🇪", code: "VE" },
  "YY": { name: "Venezuela", flag: "🇻🇪", code: "VE" },
  "YW": { name: "Venezuela", flag: "🇻🇪", code: "VE" },
  "4M": { name: "Venezuela", flag: "🇻🇪", code: "VE" },
  "CX": { name: "Uruguay", flag: "🇺🇾", code: "UY" },
  "CV": { name: "Uruguay", flag: "🇺🇾", code: "UY" },
  "CW": { name: "Uruguay", flag: "🇺🇾", code: "UY" },
  "PZ": { name: "Suriname", flag: "🇸🇷", code: "SR" },
  "8R": { name: "Guyana", flag: "🇬🇾", code: "GY" },

  // --- Central America & Caribbean ---
  "XE": { name: "Mexiko", flag: "🇲🇽", code: "MX" },
  "XF": { name: "Mexiko", flag: "🇲🇽", code: "MX" },
  "4A": { name: "Mexiko", flag: "🇲🇽", code: "MX" },
  "4B": { name: "Mexiko", flag: "🇲🇽", code: "MX" },
  "4C": { name: "Mexiko", flag: "🇲🇽", code: "MX" },
  "6D": { name: "Mexiko", flag: "🇲🇽", code: "MX" },
  "TI9": { name: "Cocos Island", flag: "🇨🇷", code: "CR" },
  "TI": { name: "Costa Rica", flag: "🇨🇷", code: "CR" },
  "TE": { name: "Costa Rica", flag: "🇨🇷", code: "CR" },
  "HP": { name: "Panama", flag: "🇵🇦", code: "PA" },
  "HO": { name: "Panama", flag: "🇵🇦", code: "PA" },
  "3E": { name: "Panama", flag: "🇵🇦", code: "PA" },
  "3F": { name: "Panama", flag: "🇵🇦", code: "PA" },
  "HI": { name: "Dominikanische Republik", flag: "🇩🇴", code: "DO" },
  "CO": { name: "Kuba", flag: "🇨🇺", code: "CU" },
  "CM": { name: "Kuba", flag: "🇨🇺", code: "CU" },
  "CL": { name: "Kuba", flag: "🇨🇺", code: "CU" },
  "T4": { name: "Kuba", flag: "🇨🇺", code: "CU" },
  "TG": { name: "Guatemala", flag: "🇬🇹", code: "GT" },
  "TD": { name: "Guatemala", flag: "🇬🇹", code: "GT" },
  "YS": { name: "El Salvador", flag: "🇸🇻", code: "SV" },
  "HU": { name: "El Salvador", flag: "🇸🇻", code: "SV" },
  "HR": { name: "Honduras", flag: "🇭🇳", code: "HN" },
  "HQ": { name: "Honduras", flag: "🇭🇳", code: "HN" },
  "YN": { name: "Nicaragua", flag: "🇳🇮", code: "NI" },
  "HT": { name: "Nicaragua", flag: "🇳🇮", code: "NI" },
  "V3": { name: "Belize", flag: "🇧🇿", code: "BZ" },
  "V4": { name: "St. Kitts & Nevis", flag: "🇰🇳", code: "KN" },
  "V2": { name: "Antigua & Barbuda", flag: "🇦🇬", code: "AG" },
  "J3": { name: "Grenada", flag: "🇬🇩", code: "GD" },
  "J6": { name: "St. Lucia", flag: "🇱🇨", code: "LC" },
  "J7": { name: "Dominica", flag: "🇩🇲", code: "DM" },
  "J8": { name: "St. Vincent", flag: "🇻🇨", code: "VC" },
  "8P": { name: "Barbados", flag: "🇧🇧", code: "BB" },
  "9Y": { name: "Trinidad & Tobago", flag: "🇹🇹", code: "TT" },
  "9Z": { name: "Trinidad & Tobago", flag: "🇹🇹", code: "TT" },
  "6Y": { name: "Jamaika", flag: "🇯🇲", code: "JM" },
  "HH": { name: "Haiti", flag: "🇭🇹", code: "HT" },
  "4V": { name: "Haiti", flag: "🇭🇹", code: "HT" },
  "C6": { name: "Bahamas", flag: "🇧🇸", code: "BS" },
  "P4": { name: "Aruba", flag: "🇦🇼", code: "AW" },

  // --- Middle East & South/Central Asia ---
  "5B": { name: "Zypern", flag: "🇨🇾", code: "CY" },
  "C4": { name: "Zypern", flag: "🇨🇾", code: "CY" },
  "P3": { name: "Zypern", flag: "🇨🇾", code: "CY" },
  "H2": { name: "Zypern", flag: "🇨🇾", code: "CY" },
  "1B": { name: "Nordzypern", flag: "🇨🇾", code: "CY" },
  "TA": { name: "Türkei", flag: "🇹🇷", code: "TR" },
  "TB": { name: "Türkei", flag: "🇹🇷", code: "TR" },
  "TC": { name: "Türkei", flag: "🇹🇷", code: "TR" },
  "YM": { name: "Türkei", flag: "🇹🇷", code: "TR" },
  "4X": { name: "Israel", flag: "🇮🇱", code: "IL" },
  "4Z": { name: "Israel", flag: "🇮🇱", code: "IL" },
  "OD": { name: "Libanon", flag: "🇱🇧", code: "LB" },
  "YK": { name: "Syrien", flag: "🇸🇾", code: "SY" },
  "JY": { name: "Jordanien", flag: "🇯🇴", code: "JO" },
  "HZ": { name: "Saudi-Arabien", flag: "🇸🇦", code: "SA" },
  "7Z": { name: "Saudi-Arabien", flag: "🇸🇦", code: "SA" },
  "8Z": { name: "Saudi-Arabien", flag: "🇸🇦", code: "SA" },
  "9K": { name: "Kuwait", flag: "🇰🇼", code: "KW" },
  "A4": { name: "Oman", flag: "🇴🇲", code: "OM" },
  "A6": { name: "VAE", flag: "🇦🇪", code: "AE" },
  "A7": { name: "Katar", flag: "🇶🇦", code: "QA" },
  "A9": { name: "Bahrain", flag: "🇧🇭", code: "BH" },
  "YI": { name: "Irak", flag: "🇮🇶", code: "IQ" },
  "EP": { name: "Iran", flag: "🇮🇷", code: "IR" },
  "EQ": { name: "Iran", flag: "🇮🇷", code: "IR" },
  "EX": { name: "Kirgisistan", flag: "🇰🇬", code: "KG" },
  "EY": { name: "Tadschikistan", flag: "🇹🇯", code: "TJ" },
  "EZ": { name: "Turkmenistan", flag: "🇹🇲", code: "TM" },
  "UK": { name: "Usbekistan", flag: "🇺🇿", code: "UZ" },
  "UN": { name: "Kasachstan", flag: "🇰🇿", code: "KZ" },
  "UP": { name: "Kasachstan", flag: "🇰🇿", code: "KZ" },
  "UQ": { name: "Kasachstan", flag: "🇰🇿", code: "KZ" },
  "UL": { name: "Kasachstan", flag: "🇰🇿", code: "KZ" },
  "4J": { name: "Aserbaidschan", flag: "🇦🇿", code: "AZ" },
  "4K": { name: "Aserbaidschan", flag: "🇦🇿", code: "AZ" },
  "EK": { name: "Armenien", flag: "🇦🇲", code: "AM" },
  "4L": { name: "Georgien", flag: "🇬🇪", code: "GE" },
  "VU": { name: "Indien", flag: "🇮🇳", code: "IN" },
  "4S": { name: "Sri Lanka", flag: "🇱🇰", code: "LK" },
  "S2": { name: "Bangladesch", flag: "🇧🇩", code: "BD" },
  "AP": { name: "Pakistan", flag: "🇵🇰", code: "PK" },
  "AR": { name: "Pakistan", flag: "🇵🇰", code: "PK" },
  "AS": { name: "Pakistan", flag: "🇵🇰", code: "PK" },
  "A5": { name: "Bhutan", flag: "🇧🇹", code: "BT" },
  "9N": { name: "Nepal", flag: "🇳🇵", code: "NP" },
  "XZ": { name: "Myanmar", flag: "🇲🇲", code: "MM" },
  "HS": { name: "Thailand", flag: "🇹🇭", code: "TH" },
  "E2": { name: "Thailand", flag: "🇹🇭", code: "TH" },
  "XU": { name: "Kambodscha", flag: "🇰🇭", code: "KH" },
  "XW": { name: "Laos", flag: "🇱🇦", code: "LA" },
  "XV": { name: "Vietnam", flag: "🇻🇳", code: "VN" },
  "3W": { name: "Vietnam", flag: "🇻🇳", code: "VN" },
  "9M": { name: "Malaysia", flag: "🇲🇾", code: "MY" },
  "9W": { name: "Malaysia", flag: "🇲🇾", code: "MY" },
  "9V": { name: "Singapur", flag: "🇸🇬", code: "SG" },
  "V8": { name: "Brunei", flag: "🇧🇳", code: "BN" },
  "YB": { name: "Indonesien", flag: "🇮🇩", code: "ID" },
  "YC": { name: "Indonesien", flag: "🇮🇩", code: "ID" },
  "YD": { name: "Indonesien", flag: "🇮🇩", code: "ID" },
  "YE": { name: "Indonesien", flag: "🇮🇩", code: "ID" },
  "YF": { name: "Indonesien", flag: "🇮🇩", code: "ID" },
  "YG": { name: "Indonesien", flag: "🇮🇩", code: "ID" },
  "YH": { name: "Indonesien", flag: "🇮🇩", code: "ID" },
  "7A": { name: "Indonesien", flag: "🇮🇩", code: "ID" },
  "7B": { name: "Indonesien", flag: "🇮🇩", code: "ID" },
  "8A": { name: "Indonesien", flag: "🇮🇩", code: "ID" },
  "8B": { name: "Indonesien", flag: "🇮🇩", code: "ID" },
  "DU": { name: "Philippinen", flag: "🇵🇭", code: "PH" },
  "DV": { name: "Philippinen", flag: "🇵🇭", code: "PH" },
  "DW": { name: "Philippinen", flag: "🇵🇭", code: "PH" },
  "DX": { name: "Philippinen", flag: "🇵🇭", code: "PH" },
  "DY": { name: "Philippinen", flag: "🇵🇭", code: "PH" },
  "DZ": { name: "Philippinen", flag: "🇵🇭", code: "PH" },
  "4D": { name: "Philippinen", flag: "🇵🇭", code: "PH" },
  "4E": { name: "Philippinen", flag: "🇵🇭", code: "PH" },
  "4F": { name: "Philippinen", flag: "🇵🇭", code: "PH" },
  "4G": { name: "Philippinen", flag: "🇵🇭", code: "PH" },
  "4W": { name: "Osttimor", flag: "🇹🇱", code: "TL" },

  // --- Africa ---
  "ZS8": { name: "Prinz-Edward-Inseln", flag: "🇿🇦", code: "ZA" },
  "ZS": { name: "Südafrika", flag: "🇿🇦", code: "ZA" },
  "ZR": { name: "Südafrika", flag: "🇿🇦", code: "ZA" },
  "ZU": { name: "Südafrika", flag: "🇿🇦", code: "ZA" },
  "ZT": { name: "Südafrika", flag: "🇿🇦", code: "ZA" },
  "5N": { name: "Nigeria", flag: "🇳🇬", code: "NG" },
  "ET": { name: "Äthiopien", flag: "🇪🇹", code: "ET" },
  "E3": { name: "Eritrea", flag: "🇪🇷", code: "ER" },
  "SU": { name: "Ägypten", flag: "🇪🇬", code: "EG" },
  "6A": { name: "Ägypten", flag: "🇪🇬", code: "EG" },
  "CN": { name: "Marokko", flag: "🇲🇦", code: "MA" },
  "5C": { name: "Marokko", flag: "🇲🇦", code: "MA" },
  "5D": { name: "Marokko", flag: "🇲🇦", code: "MA" },
  "5E": { name: "Marokko", flag: "🇲🇦", code: "MA" },
  "7X": { name: "Algerien", flag: "🇩🇿", code: "DZ" },
  "7T": { name: "Algerien", flag: "🇩🇿", code: "DZ" },
  "3V": { name: "Tunesien", flag: "🇹🇳", code: "TN" },
  "TS": { name: "Tunesien", flag: "🇹🇳", code: "TN" },
  "5A": { name: "Libyen", flag: "🇱🇾", code: "LY" },
  "S0": { name: "Westsahara", flag: "🇪🇭", code: "EH" },
  "5T": { name: "Mauretanien", flag: "🇲🇷", code: "MR" },
  "6W": { name: "Senegal", flag: "🇸🇳", code: "SN" },
  "6V": { name: "Senegal", flag: "🇸🇳", code: "SN" },
  "C5": { name: "Gambia", flag: "🇬🇲", code: "GM" },
  "3X": { name: "Guinea", flag: "🇬🇳", code: "GN" },
  "J5": { name: "Guinea-Bissau", flag: "🇬🇼", code: "GW" },
  "TU": { name: "Elfenbeinküste", flag: "🇨🇮", code: "CI" },
  "EL": { name: "Liberia", flag: "🇱🇷", code: "LR" },
  "9L": { name: "Sierra Leone", flag: "🇸🇱", code: "SL" },
  "9G": { name: "Ghana", flag: "🇬🇭", code: "GH" },
  "5V": { name: "Togo", flag: "🇹🇬", code: "TG" },
  "TY": { name: "Benin", flag: "🇧🇯", code: "BJ" },
  "5U": { name: "Niger", flag: "🇳🇪", code: "NE" },
  "XT": { name: "Burkina Faso", flag: "🇧🇫", code: "BF" },
  "TT": { name: "Tschad", flag: "🇹🇩", code: "TD" },
  "TL": { name: "Zentralafrika", flag: "🇨🇫", code: "CF" },
  "9Q": { name: "DR Kongo", flag: "🇨🇩", code: "CD" },
  "TN": { name: "Republik Kongo", flag: "🇨🇬", code: "CG" },
  "TR": { name: "Gabun", flag: "🇬🇦", code: "GA" },
  "TJ": { name: "Kamerun", flag: "🇨🇲", code: "CM" },
  "3C0": { name: "Annobon", flag: "🇬🇶", code: "GQ" },
  "3C": { name: "Äquatorialguinea", flag: "🇬🇶", code: "GQ" },
  "S9": { name: "São Tomé & Príncipe", flag: "🇸🇹", code: "ST" },
  "D2": { name: "Angola", flag: "🇦🇴", code: "AO" },
  "D3": { name: "Angola", flag: "🇦🇴", code: "AO" },
  "V5": { name: "Namibia", flag: "🇳🇦", code: "NA" },
  "A2": { name: "Botswana", flag: "🇧🇼", code: "BW" },
  "7P": { name: "Lesotho", flag: "🇱🇸", code: "LS" },
  "3DA": { name: "Eswatini", flag: "🇸🇿", code: "SZ" },
  "Z2": { name: "Simbabwe", flag: "🇿🇼", code: "ZW" },
  "9J": { name: "Sambia", flag: "🇿🇲", code: "ZM" },
  "9X": { name: "Ruanda", flag: "🇷🇼", code: "RW" },
  "9U": { name: "Burundi", flag: "🇧🇮", code: "BI" },
  "5X": { name: "Uganda", flag: "🇺🇬", code: "UG" },
  "5H": { name: "Tansania", flag: "🇹🇿", code: "TZ" },
  "5I": { name: "Tansania", flag: "🇹🇿", code: "TZ" },
  "5Z": { name: "Kenia", flag: "🇰🇪", code: "KE" },
  "5Y": { name: "Kenia", flag: "🇰🇪", code: "KE" },
  "T5": { name: "Somalia", flag: "🇸🇴", code: "SO" },
  "6O": { name: "Somalia", flag: "🇸🇴", code: "SO" },
  "J2": { name: "Dschibuti", flag: "🇩🇯", code: "DJ" },
  "ST": { name: "Sudan", flag: "🇸🇩", code: "SD" },
  "Z8": { name: "Südsudan", flag: "🇸🇸", code: "SS" },
  "7Q": { name: "Malawi", flag: "🇲🇼", code: "MW" },
  "C8": { name: "Mosambik", flag: "🇲🇿", code: "MZ" },
  "C9": { name: "Mosambik", flag: "🇲🇿", code: "MZ" },
  "3B8": { name: "Mauritius", flag: "🇲🇺", code: "MU" },
  "3B9": { name: "Rodrigues-Insel", flag: "🇲🇺", code: "MU" },
  "3B7": { name: "St. Brandon / Agalega", flag: "🇲🇺", code: "MU" },
  "S7": { name: "Seychellen", flag: "🇸🇨", code: "SC" },
  "VQ9": { name: "Chagos (Diego Garcia)", flag: "🇮🇴", code: "IO" },
  "D6": { name: "Komoren", flag: "🇰🇲", code: "KM" },
  "5R": { name: "Madagaskar", flag: "🇲🇬", code: "MG" },
  "5S": { name: "Madagaskar", flag: "🇲🇬", code: "MG" },

  // --- International / Antarctica ---
  "4U1UN": { name: "UNHQ New York", flag: "🇺🇳", code: "UN" },
  "4U1ITU": { name: "ITU Genf", flag: "🇺🇳", code: "UN" },
  "4U": { name: "Vereinte Nationen", flag: "🇺🇳", code: "UN" },
  "DP0": { name: "Antarktis (Neumayer)", flag: "🇦🇶", code: "AQ" },
  "DP1": { name: "Antarktis", flag: "🇦🇶", code: "AQ" },
  "RI1AN": { name: "Antarktis", flag: "🇦🇶", code: "AQ" },
  "KC4": { name: "Antarktis (US)", flag: "🇦🇶", code: "AQ" },
};

// Sorted list of prefixes (longest first) for exact greedy matching
const SORTED_PREFIXES = Object.keys(DXCC_MAP).sort((a, b) => b.length - a.length);

// Standard non-country callsign modifiers
const IGNORED_SUFFIXES = new Set([
  "P", "M", "MM", "AM", "QRP", "LGT", "LH", "B", "R", "FF", 
  "SOTA", "IOTA", "JOTA", "YOTA", "A", "PORTABLE", "MOBILE"
]);

/**
 * Parses an amateur radio callsign to find its DXCC country and flag.
 * Handles portable prefixes (e.g. EA8/DL1ABC, DL1ABC/EA8, W4/G3TXF, etc.)
 */
export const getCountryInfoByCallsign = (callsign: string): DXCCInfo => {
  if (!callsign) return { prefix: "", name: "Unbekannt", flag: "🏳️", code: "UN" };

  const rawCall = callsign.trim().toUpperCase();

  // If callsign has multiple parts separated by '/'
  if (rawCall.includes("/")) {
    const parts = rawCall.split("/").filter(p => p.length > 0);
    
    // Filter out common operational suffixes like /P, /M, /MM, /QRP, etc.
    const relevantParts = parts.filter(p => !IGNORED_SUFFIXES.has(p) && !/^\d$/.test(p));

    if (relevantParts.length > 1) {
      // 1. Check if first part is a geographic prefix (e.g., EA8/DL1ABC, SV9/OK1KIR, IS0/IZ2XYZ)
      // Usually shorter than the base callsign or pure prefix (2-4 chars)
      const firstPart = relevantParts[0];
      const matchFirst = matchPrefix(firstPart);
      
      // If the first part looks like a guest country prefix and second part has letters/numbers (a full call)
      if (matchFirst && (firstPart.length <= 4 || firstPart.length < relevantParts[1].length)) {
        return matchFirst;
      }

      // 2. Check if second part is a geographic modifier (e.g., DL1ABC/EA8, F5XYZ/TK)
      const secondPart = relevantParts[1];
      const matchSecond = matchPrefix(secondPart);
      if (matchSecond && (secondPart.length <= 4 || secondPart.length < relevantParts[0].length)) {
        return matchSecond;
      }
    }

    // Fallback: check all non-ignored parts
    for (const part of relevantParts) {
      const match = matchPrefix(part);
      if (match) return match;
    }
  }

  // Single callsign or fallback
  const directMatch = matchPrefix(rawCall);
  if (directMatch) return directMatch;

  return { prefix: "", name: "Unbekannt", flag: "🏳️", code: "UN" };
};

/**
 * Greedily matches the callsign or prefix against the DXCC database.
 */
function matchPrefix(str: string): DXCCInfo | null {
  if (!str) return null;
  const cleanStr = str.trim().toUpperCase();

  for (const prefix of SORTED_PREFIXES) {
    if (cleanStr.startsWith(prefix)) {
      return {
        prefix,
        ...DXCC_MAP[prefix]
      };
    }
  }
  return null;
}
